nginxIngressController:
  controller:
    ingressClassResource:
      name: nginx2
      controllerValue: "k8s.io/nginx2"
nginxIngress:
  name: nginx-ingress
  rules:
  - host: "example.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
