apiVersion: v1
kind: Pod
metadata:
  name: debian 
  labels:
    name: debian 
spec:
  containers:
  - name: debian 
    image: debian
    command: ["/bin/sh"]
    args: ["-c", "echo", "{{ .Values.name }}"]
  terminationGracePeriodSeconds: 60


