apiVersion: v1
kind: Pod
metadata:
  name: debian 
  labels:
    name: debian 
spec:
  containers:
  - name: debian 
    image: debian
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
  terminationGracePeriodSeconds: 60

